backend:
  name: git-gateway
  branch: master
media_folder: source/images
public_folder: /images
collections:
  - name: all_posts
    fields: &ref_0
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: HH:mm:ss
        format: YYYY-MM-DD HH:mm:ss
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Permalink
        name: permalink
        widget: string
        required: false
      - label: Comments
        name: comments
        widget: boolean
        default: true
        required: false
    label: Post
    folder: source/_posts
    create: true
    editor:
      preview: true
  - label: Page
    name: pages
    delete: false
    files:
      - name: categories-index.md
        label: categories
        file: source\categories\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: collect-index.md
        label: collect
        file: source\collect\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: archives-index.md
        label: archives
        file: source\archives\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: link-index.md
        label: friends
        file: source\link\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: scenery-index.md
        label: scenery
        file: source\scenery\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: messageboard-index.md
        label: messageboard
        file: source\messageboard\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: photography-index.md
        label: 随手拍
        file: source\photography\index.md
        editor:
          preview: true
        fields: *ref_0
      - name: tags-index.md
        label: tags
        file: source\tags\index.md
        editor:
          preview: true
        fields: *ref_0
